tunnel: 939b16f7-7d13-4776-bd4d-80fe8021fc72
credentials-file: /home/ubuntu/.cloudflared/939b16f7-7d13-4776-bd4d-80fe8021fc72.json
ingress:
  - hostname: www.rootrecord.cloud
    service: http://127.0.0.1:8090
  - service: http_status:404
